imports:
    - { resource: 'config.yml' }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

parameters:
    database_name:          'bamibot'
    database_user:          'bamibot'
    database_password:      'S!fsU9b)ubG}aiwcd,85X@e['

monolog:
    use_microseconds: false
    channels: [ 'api_ai' ]
    handlers:
        # \Default logging channel
        channel_default:
            type:           'fingers_crossed'
            handler:        'channel_default_rotating_file'
            action_level:   'error'
            channels:       [ '!api_ai', '!php' ]
            excluded_404s:
                - ^/
        channel_default_rotating_file:
            type:           'rotating_file'
            path:           '%kernel.logs_dir%/%kernel.environment%.log'
            max_files:      14
            level:          'debug'
        # /Default logging channel

        # \Stream loggers - simple file logs for specific channels
        channel_api_ai:
            type:           'stream'
            path:           '%kernel.logs_dir%/api_ai.log'
            channels:       [ 'api_ai' ]
        # /Stream loggers
