default:
    path:     /
    defaults: { _controller: bami_api.controller.default:indexAction }

callback:
    path:     /callback
    defaults: { _controller: bami_api.controller.default:callbackAction }
